version: "3"
services:
  checkout:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
    command: sleep infinity
    links:
      - mongo
      - astparser
  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - /data/db
  astparser:
    image: shinhwagk/miastparser:0.0.1
