POST http://127.0.0.1:7000/git HTTP/1.1
Content-Type: application/json

{
  "sha": "1111",
  "sqls": [
    {
      "text": "create table a.11bc(a int)",
      "inspect": ""
    },
    {
      "text": "create table a.11b1c(a int)",
      "inspect": "222"
    }
  ]
}