name: sql executer
on: [push]
jobs:
  build-sqlexecuter:
    runs-on: ubuntu-latest
    services:
      nginx:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306
    env:
      NGINX_PORT: 80
    steps:
      - name: Verify MySQL connection from host
        run: |
          sudo apt-get install -y mysql-client
          mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uroot -ppassword -e "SHOW DATABASES"
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: "3.8"
          architecture: "x64"
      - name: Install dependencies
        working-directory: ./src/sqlexecuter
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test
        working-directory: ./src/sqlexecuter
        run: python main_test.py
