name: sql executer
on: [push]
jobs:
  build-sqlexecuter:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/cache@v1
        name: xxxx
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: "3.8"
          architecture: "x64"
      - name: Install dependencies
        working-directory: ./src/sqlexecuter
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test
        working-directory: ./src/sqlexecuter
        env:
          port: ${{ job.services.mysql.ports['3306'] }}
        run: |
          mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uroot -ppassword -e "SHOW DATABASES"
          python main_test.py
