name: sql executer
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: "3.8"
          architecture: "x64"
      - name: Install dependencies
        working-directory: ./src/sqlexecuter
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python main_test.py
